# Generated by Django 3.0.8 on 2020-07-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('releaseId', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=50)),
                ('have', models.IntegerField()),
                ('want', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
